#
# Copyright (c) 2017 Raytheon BBN Technologies
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this 
# software and/or hardware specification (the “Work”) to deal in the Work without 
# restriction, including without limitation the rights to use, copy, modify, merge, 
# publish, distribute, sublicense, and/or sell copies of the Work, and to permit 
# persons to whom the Work is furnished to do so, subject to the following conditions:  
# 
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Work.  
# 
# THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE WORK 
# OR THE USE OR OTHER DEALINGS IN THE WORK. 
#
---
- name: Custodian
  hosts: Custodian
  become: true
  become_method: sudo
  tasks:
   - name: Restart NDN Daemon
     shell: ./install_script.sh
     args:
       chdir: /local
     register: cust
   - debug: var=cust.stdout_lines

   - name: Start the Producer Application
     command: python producer.py -n /nytimes
     args:
      chdir: /local
     async: 3600
     poll: 0
     register: cst
   - debug: var=cst.stdout_lines


- name: Experimenter
  hosts: Experimenter
  become: true
  become_method: sudo
  tasks:  
   - name: Start the consumer application
     command: python /local/consumer.py -u /nytimes/Math
     register: expt
     failed_when: "'TIMEOUT' in expt.stdout"
   - debug: var=expt.stdout_lines

- name: PI
  hosts: PI
  become: true
  become_method: sudo
  tasks:
   - name: Start the Consumer Application
     command: python /local/consumer.py -u /nytimes/Science
     register: pi
     failed_when: "'TIMEOUT' in pi.stdout"
   - debug: var=pi.stdout_lines     

