#
# Copyright (c) 2017 Raytheon BBN Technologies
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this 
# software and/or hardware specification (the “Work”) to deal in the Work without 
# restriction, including without limitation the rights to use, copy, modify, merge, 
# publish, distribute, sublicense, and/or sell copies of the Work, and to permit 
# persons to whom the Work is furnished to do so, subject to the following conditions:  
# 
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Work.  
# 
# THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE WORK 
# OR THE USE OR OTHER DEALINGS IN THE WORK. 
#
---
- name: S2
  hosts: host2
  tasks: [ ]

- name: destination
  hosts: host3
  tasks: [ ]

- name: S1
  hosts: host1
  tasks:
   - name: ping S2
     command: ping host2 -c 10
     register: S1
     failed_when: "' 0% packet loss' in S1.stdout"
   - debug: var=S1.stdout_lines
   - pause:
       seconds: 300


- name: Controller
  hosts: Controller
  tasks:
  - name: Checking if RYU installed
    stat:
      path: /tmp/ryu/ryu/app/simple_switch.py
    register: ryu
    failed_when: not ryu.stat.exists 
  - name: Start RYU Controller
    command: ./bin/ryu-manager ryu/app/simple_switch.py
    args:
      chdir: /tmp/ryu/ 
    async: 3600
    poll: 0
    register: ryu
  - debug: var=ryu.stdout_lines
  - pause:
      seconds: 300

- name: switch
  hosts: OVS
  become: true
  become_method: sudo
  tasks:
  - name: add ovs-br
    command: ovs-vsctl add-br br0

  - name: disable ip address of eth1
    command: ifconfig eth1 0

  - name: disable ip address of eth2
    command: ifconfig eth2 0

  - name: disable ip address of eth3
    command: ifconfig eth3 0

  - name: add eth1 to br
    command: ovs-vsctl add-port br0 eth1

  - name: add eth2 to br
    command: ovs-vsctl add-port br0 eth2

  - name: add eth3 to br
    command: ovs-vsctl add-port br0 eth3


  - name: set controller
    command: ovs-vsctl set-controller br0 tcp:{{ hostvars['Controller']['ansible_eth0']['ipv4']['address'] }}:6633

  - name: set fail-mode
    command: ovs-vsctl set-fail-mode br0 secure

- name: S1
  hosts: host1
  tasks:
   - name: ping host2
     command: ping host2 -c 10
     register: S1
     failed_when: "'Destination Host Unreachable' in S1.stdout"
   - debug: var=S1.stdout_lines

   - name: ping destination
     command: ping host3 -c 10
     register: S1
     failed_when: "'Destination Host Unreachable' in S1.stdout"
   - debug: var=S1.stdout_lines
   
